spring.application.name=aiimage
spring.mongodb.uri=mongodb+srv://aiadmin:qwer1234@seung0531.iuujfry.mongodb.net/aiimage?retryWrites=true&w=majority&appName=seung0531
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.cookie.secure=false
logging.level.org.springframework.security=TRACE
comfy.output-dir=${C:\Users\dbstn\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\output}
